project:
  type: book
# resources:
#   - "*.wav"
# embed-resources: true
# Book Options

book:
  title: "The FND Information Course"
  subtitle: "An Online Resource"
  description: "An online information course to help guide you through management of functional neurological disorder."
  author:
    - "Dr. Antonia Kirkby"
    - "Emily Lamb"
  contributor: "Dr. Chris Gaskell"
  date: last-modified
  date-format: "[Last compiled on] D MMMM, YYYY"
  cover-image: "img/front-border.JPEG"
  image: "img/front-border.JPEG"
  version: 1
  chapter-number: "chapter"
  event-place: "Stoke"
  #sharing: twitter
  downloads: [pdf, epub, docx]
  twitter-card: true
  site-url: "https://fnd-self-help.netlify.app"
  #card-style: "summary_large_image"
  navbar:
    search: true
    #logo: "nhs.logo.jpg"
  sidebar:
    pinned: false
    style: docked
    foreground: "#009adb"
    logo: "nhs.logo.jpg"
  page-footer:
    center:
      - text: "An Intervention Developed by North Staffordshire NHS Foundation Trust"
    background: "#2fa4e7"
    foreground: white



# Structure

  chapters:
    - index.qmd
    - part: content/part_1/part_1.qmd
      chapters:
        - content/part_1/1_introduction.qmd
        - content/part_1/2_experiences.qmd
        - content/part_1/3_development.qmd
        - content/part_1/4_tiger.qmd
        - content/part_1/5_traffic_lights.qmd
        - content/part_1/6_thoughts_feelings.qmd
        - content/part_1/7_green_zone.qmd
    - part: content/part_2/part_2.qmd
      chapters:
        - content/part_2/8_breathing.qmd
        - content/part_2/9_relaxation.qmd
        - content/part_2/10_strategies.qmd
        - content/part_2/11_lifestyle.qmd
    - content/summary.qmd
    - content/resources.qmd
      #     - references.qmd

# Render Options

format:
  html:
    theme:
      light: [cerulean, styles.scss]
      dark: darkly
    css: styles.cssx
    #fontcolor: black
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    toc-location: right
    number-depth: 1
  # titlepage-pdf:
  #   coverpage: true
  #   cover-bg-image: "myimage.jpeg"
  #   #cover-bg-image: "img/front page.jpg"
  #   documentclass: scrreprt
  #   classoption: ["oneside", "open=any"]
  #   number-sections: true
  #   self-contained: true
  #docx: default
  pdf:
    documentclass: scrreprt
    output-file: "FND Self Help"
    toc-depth: 2
    number-depth: 1
    toc-title: "Contents"
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex
#epub: default

editor: visual
bibliography: [bib/packages.bib]
csl: csl/apa7.csl
classoption: openany
knitr:
  opts_chunk:
    echo: false
    messages: false
    warnings: false
number-sections: true
link-citations: true
biblio-style: apalike
fig-cap-location: top
tbl-cap-location: top
tbl-colwidths: true
prefer-html: true
